// Code generated by protoc-gen-go. DO NOT EDIT.
// source: page.proto

package cloudwalker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RowLayout int32

const (
	RowLayout_Landscape RowLayout = 0
	RowLayout_Portrait  RowLayout = 1
	RowLayout_Square    RowLayout = 2
	RowLayout_Circle    RowLayout = 3
)

var RowLayout_name = map[int32]string{
	0: "Landscape",
	1: "Portrait",
	2: "Square",
	3: "Circle",
}

var RowLayout_value = map[string]int32{
	"Landscape": 0,
	"Portrait":  1,
	"Square":    2,
	"Circle":    3,
}

func (x RowLayout) String() string {
	return proto.EnumName(RowLayout_name, int32(x))
}

func (RowLayout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{0}
}

type RowType int32

const (
	RowType_Editorial         RowType = 0
	RowType_Recommendation_CB RowType = 1
	RowType_Dynamic           RowType = 2
	RowType_Recommendation_CF RowType = 3
	RowType_Web               RowType = 4
)

var RowType_name = map[int32]string{
	0: "Editorial",
	1: "Recommendation_CB",
	2: "Dynamic",
	3: "Recommendation_CF",
	4: "Web",
}

var RowType_value = map[string]int32{
	"Editorial":         0,
	"Recommendation_CB": 1,
	"Dynamic":           2,
	"Recommendation_CF": 3,
	"Web":               4,
}

func (x RowType) String() string {
	return proto.EnumName(RowType_name, int32(x))
}

func (RowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{1}
}

type Monetize int32

const (
	Monetize_Free         Monetize = 0
	Monetize_Paid         Monetize = 1
	Monetize_Subscription Monetize = 2
	Monetize_Rent         Monetize = 3
)

var Monetize_name = map[int32]string{
	0: "Free",
	1: "Paid",
	2: "Subscription",
	3: "Rent",
}

var Monetize_value = map[string]int32{
	"Free":         0,
	"Paid":         1,
	"Subscription": 2,
	"Rent":         3,
}

func (x Monetize) String() string {
	return proto.EnumName(Monetize_name, int32(x))
}

func (Monetize) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{2}
}

type TileType int32

const (
	TileType_ImageTile     TileType = 0
	TileType_VideoTile     TileType = 1
	TileType_FeatureTile   TileType = 2
	TileType_AdvertiseTile TileType = 3
	TileType_CarouselTile  TileType = 4
)

var TileType_name = map[int32]string{
	0: "ImageTile",
	1: "VideoTile",
	2: "FeatureTile",
	3: "AdvertiseTile",
	4: "CarouselTile",
}

var TileType_value = map[string]int32{
	"ImageTile":     0,
	"VideoTile":     1,
	"FeatureTile":   2,
	"AdvertiseTile": 3,
	"CarouselTile":  4,
}

func (x TileType) String() string {
	return proto.EnumName(TileType_name, int32(x))
}

func (TileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{3}
}

type Page struct {
	PageName             string               `protobuf:"bytes,1,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	PageLogo             string               `protobuf:"bytes,3,opt,name=page_logo,json=pageLogo,proto3" json:"page_logo,omitempty"`
	Row                  []*Row               `protobuf:"bytes,4,rep,name=row,proto3" json:"row,omitempty"`
	Carousel             []*Carousel          `protobuf:"bytes,5,rep,name=carousel,proto3" json:"carousel,omitempty"`
	PageId               string               `protobuf:"bytes,6,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *Page) GetPageLogo() string {
	if m != nil {
		return m.PageLogo
	}
	return ""
}

func (m *Page) GetRow() []*Row {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *Page) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *Page) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *Page) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Page) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Carousel struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Package              string   `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Index                int32    `protobuf:"varint,5,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Carousel) Reset()         { *m = Carousel{} }
func (m *Carousel) String() string { return proto.CompactTextString(m) }
func (*Carousel) ProtoMessage()    {}
func (*Carousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{1}
}

func (m *Carousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carousel.Unmarshal(m, b)
}
func (m *Carousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carousel.Marshal(b, m, deterministic)
}
func (m *Carousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carousel.Merge(m, src)
}
func (m *Carousel) XXX_Size() int {
	return xxx_messageInfo_Carousel.Size(m)
}
func (m *Carousel) XXX_DiscardUnknown() {
	xxx_messageInfo_Carousel.DiscardUnknown(m)
}

var xxx_messageInfo_Carousel proto.InternalMessageInfo

func (m *Carousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Carousel) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Carousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Carousel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Carousel) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Row struct {
	RowLayout            RowLayout                  `protobuf:"varint,1,opt,name=row_layout,json=rowLayout,proto3,enum=cloudwalker.RowLayout" json:"row_layout,omitempty"`
	RowName              string                     `protobuf:"bytes,2,opt,name=row_name,json=rowName,proto3" json:"row_name,omitempty"`
	RowIndex             int32                      `protobuf:"varint,3,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	RowFilters           map[string]*RowFilterValue `protobuf:"bytes,4,rep,name=row_filters,json=rowFilters,proto3" json:"row_filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RowSort              map[string]int32           `protobuf:"bytes,5,rep,name=row_sort,json=rowSort,proto3" json:"row_sort,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
	RowTileIds           []string                   `protobuf:"bytes,6,rep,name=row_tile_ids,json=rowTileIds,proto3" json:"row_tile_ids,omitempty"`
	RowType              RowType                    `protobuf:"varint,7,opt,name=row_type,json=rowType,proto3,enum=cloudwalker.RowType" json:"row_type,omitempty"`
	Shuffle              bool                       `protobuf:"varint,8,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-" bson:"-"`
	XXX_unrecognized     []byte                     `json:"-" bson:"-"`
	XXX_sizecache        int32                      `json:"-" bson:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{2}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetRowLayout() RowLayout {
	if m != nil {
		return m.RowLayout
	}
	return RowLayout_Landscape
}

func (m *Row) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *Row) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

func (m *Row) GetRowFilters() map[string]*RowFilterValue {
	if m != nil {
		return m.RowFilters
	}
	return nil
}

func (m *Row) GetRowSort() map[string]int32 {
	if m != nil {
		return m.RowSort
	}
	return nil
}

func (m *Row) GetRowTileIds() []string {
	if m != nil {
		return m.RowTileIds
	}
	return nil
}

func (m *Row) GetRowType() RowType {
	if m != nil {
		return m.RowType
	}
	return RowType_Editorial
}

func (m *Row) GetShuffle() bool {
	if m != nil {
		return m.Shuffle
	}
	return false
}

type RowFilterValue struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RowFilterValue) Reset()         { *m = RowFilterValue{} }
func (m *RowFilterValue) String() string { return proto.CompactTextString(m) }
func (*RowFilterValue) ProtoMessage()    {}
func (*RowFilterValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{3}
}

func (m *RowFilterValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowFilterValue.Unmarshal(m, b)
}
func (m *RowFilterValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowFilterValue.Marshal(b, m, deterministic)
}
func (m *RowFilterValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowFilterValue.Merge(m, src)
}
func (m *RowFilterValue) XXX_Size() int {
	return xxx_messageInfo_RowFilterValue.Size(m)
}
func (m *RowFilterValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RowFilterValue.DiscardUnknown(m)
}

var xxx_messageInfo_RowFilterValue proto.InternalMessageInfo

func (m *RowFilterValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// get Page input
type GetPageReq struct {
	PageId               string   `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetPageReq) Reset()         { *m = GetPageReq{} }
func (m *GetPageReq) String() string { return proto.CompactTextString(m) }
func (*GetPageReq) ProtoMessage()    {}
func (*GetPageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{4}
}

func (m *GetPageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageReq.Unmarshal(m, b)
}
func (m *GetPageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageReq.Marshal(b, m, deterministic)
}
func (m *GetPageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageReq.Merge(m, src)
}
func (m *GetPageReq) XXX_Size() int {
	return xxx_messageInfo_GetPageReq.Size(m)
}
func (m *GetPageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageReq proto.InternalMessageInfo

func (m *GetPageReq) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

type DeletePageReq struct {
	PageId               string   `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeletePageReq) Reset()         { *m = DeletePageReq{} }
func (m *DeletePageReq) String() string { return proto.CompactTextString(m) }
func (*DeletePageReq) ProtoMessage()    {}
func (*DeletePageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{5}
}

func (m *DeletePageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePageReq.Unmarshal(m, b)
}
func (m *DeletePageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePageReq.Marshal(b, m, deterministic)
}
func (m *DeletePageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePageReq.Merge(m, src)
}
func (m *DeletePageReq) XXX_Size() int {
	return xxx_messageInfo_DeletePageReq.Size(m)
}
func (m *DeletePageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePageReq proto.InternalMessageInfo

func (m *DeletePageReq) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

type ResultPage struct {
	PageId               string       `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageName             string       `protobuf:"bytes,2,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	Carousels            []*Carousel  `protobuf:"bytes,3,rep,name=carousels,proto3" json:"carousels,omitempty"`
	Rows                 []*ResultRow `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" bson:"-"`
}

func (m *ResultPage) Reset()         { *m = ResultPage{} }
func (m *ResultPage) String() string { return proto.CompactTextString(m) }
func (*ResultPage) ProtoMessage()    {}
func (*ResultPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{6}
}

func (m *ResultPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultPage.Unmarshal(m, b)
}
func (m *ResultPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultPage.Marshal(b, m, deterministic)
}
func (m *ResultPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultPage.Merge(m, src)
}
func (m *ResultPage) XXX_Size() int {
	return xxx_messageInfo_ResultPage.Size(m)
}
func (m *ResultPage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultPage.DiscardUnknown(m)
}

var xxx_messageInfo_ResultPage proto.InternalMessageInfo

func (m *ResultPage) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *ResultPage) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *ResultPage) GetCarousels() []*Carousel {
	if m != nil {
		return m.Carousels
	}
	return nil
}

func (m *ResultPage) GetRows() []*ResultRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ResultRow struct {
	RowName              string     `protobuf:"bytes,1,opt,name=row_name,json=rowName,proto3" json:"row_name,omitempty"`
	RowIndex             int32      `protobuf:"varint,2,opt,name=row_index,json=rowIndex,proto3" json:"row_index,omitempty"`
	Tiles                []*Content `protobuf:"bytes,3,rep,name=tiles,proto3" json:"tiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-" bson:"-"`
	XXX_unrecognized     []byte     `json:"-" bson:"-"`
	XXX_sizecache        int32      `json:"-" bson:"-"`
}

func (m *ResultRow) Reset()         { *m = ResultRow{} }
func (m *ResultRow) String() string { return proto.CompactTextString(m) }
func (*ResultRow) ProtoMessage()    {}
func (*ResultRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{7}
}

func (m *ResultRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultRow.Unmarshal(m, b)
}
func (m *ResultRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultRow.Marshal(b, m, deterministic)
}
func (m *ResultRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultRow.Merge(m, src)
}
func (m *ResultRow) XXX_Size() int {
	return xxx_messageInfo_ResultRow.Size(m)
}
func (m *ResultRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultRow.DiscardUnknown(m)
}

var xxx_messageInfo_ResultRow proto.InternalMessageInfo

func (m *ResultRow) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *ResultRow) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

func (m *ResultRow) GetTiles() []*Content {
	if m != nil {
		return m.Tiles
	}
	return nil
}

// new schema
type Content struct {
	Title                string   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Poster               []string `protobuf:"bytes,1,rep,name=poster,proto3" json:"poster,omitempty"`
	Portriat             []string `protobuf:"bytes,2,rep,name=portriat,proto3" json:"portriat,omitempty"`
	Type                 TileType `protobuf:"varint,3,opt,name=type,proto3,enum=cloudwalker.TileType" json:"type,omitempty"`
	IsDetailPage         bool     `protobuf:"varint,4,opt,name=is_detail_page,json=isDetailPage,proto3" json:"is_detail_page,omitempty"`
	ContentId            string   `protobuf:"bytes,5,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Play                 []*Play  `protobuf:"bytes,6,rep,name=play,proto3" json:"play,omitempty"`
	Video                []string `protobuf:"bytes,7,rep,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{8}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Content) GetPoster() []string {
	if m != nil {
		return m.Poster
	}
	return nil
}

func (m *Content) GetPortriat() []string {
	if m != nil {
		return m.Portriat
	}
	return nil
}

func (m *Content) GetType() TileType {
	if m != nil {
		return m.Type
	}
	return TileType_ImageTile
}

func (m *Content) GetIsDetailPage() bool {
	if m != nil {
		return m.IsDetailPage
	}
	return false
}

func (m *Content) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *Content) GetPlay() []*Play {
	if m != nil {
		return m.Play
	}
	return nil
}

func (m *Content) GetVideo() []string {
	if m != nil {
		return m.Video
	}
	return nil
}

type Play struct {
	Monetize             Monetize `protobuf:"varint,5,opt,name=monetize,proto3,enum=cloudwalker.Monetize" json:"monetize,omitempty"`
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Package              string   `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Play) Reset()         { *m = Play{} }
func (m *Play) String() string { return proto.CompactTextString(m) }
func (*Play) ProtoMessage()    {}
func (*Play) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{9}
}

func (m *Play) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Play.Unmarshal(m, b)
}
func (m *Play) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Play.Marshal(b, m, deterministic)
}
func (m *Play) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Play.Merge(m, src)
}
func (m *Play) XXX_Size() int {
	return xxx_messageInfo_Play.Size(m)
}
func (m *Play) XXX_DiscardUnknown() {
	xxx_messageInfo_Play.DiscardUnknown(m)
}

var xxx_messageInfo_Play proto.InternalMessageInfo

func (m *Play) GetMonetize() Monetize {
	if m != nil {
		return m.Monetize
	}
	return Monetize_Free
}

func (m *Play) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Play) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Play) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *Play) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type DropDownReq struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DropDownReq) Reset()         { *m = DropDownReq{} }
func (m *DropDownReq) String() string { return proto.CompactTextString(m) }
func (*DropDownReq) ProtoMessage()    {}
func (*DropDownReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{10}
}

func (m *DropDownReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropDownReq.Unmarshal(m, b)
}
func (m *DropDownReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropDownReq.Marshal(b, m, deterministic)
}
func (m *DropDownReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropDownReq.Merge(m, src)
}
func (m *DropDownReq) XXX_Size() int {
	return xxx_messageInfo_DropDownReq.Size(m)
}
func (m *DropDownReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DropDownReq.DiscardUnknown(m)
}

var xxx_messageInfo_DropDownReq proto.InternalMessageInfo

func (m *DropDownReq) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type DropDownResp struct {
	Result               []string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DropDownResp) Reset()         { *m = DropDownResp{} }
func (m *DropDownResp) String() string { return proto.CompactTextString(m) }
func (*DropDownResp) ProtoMessage()    {}
func (*DropDownResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f14a105a5ef2e917, []int{11}
}

func (m *DropDownResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropDownResp.Unmarshal(m, b)
}
func (m *DropDownResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropDownResp.Marshal(b, m, deterministic)
}
func (m *DropDownResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropDownResp.Merge(m, src)
}
func (m *DropDownResp) XXX_Size() int {
	return xxx_messageInfo_DropDownResp.Size(m)
}
func (m *DropDownResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DropDownResp.DiscardUnknown(m)
}

var xxx_messageInfo_DropDownResp proto.InternalMessageInfo

func (m *DropDownResp) GetResult() []string {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterEnum("cloudwalker.RowLayout", RowLayout_name, RowLayout_value)
	proto.RegisterEnum("cloudwalker.RowType", RowType_name, RowType_value)
	proto.RegisterEnum("cloudwalker.Monetize", Monetize_name, Monetize_value)
	proto.RegisterEnum("cloudwalker.TileType", TileType_name, TileType_value)
	proto.RegisterType((*Page)(nil), "cloudwalker.Page")
	proto.RegisterType((*Carousel)(nil), "cloudwalker.Carousel")
	proto.RegisterType((*Row)(nil), "cloudwalker.Row")
	proto.RegisterMapType((map[string]*RowFilterValue)(nil), "cloudwalker.Row.RowFiltersEntry")
	proto.RegisterMapType((map[string]int32)(nil), "cloudwalker.Row.RowSortEntry")
	proto.RegisterType((*RowFilterValue)(nil), "cloudwalker.RowFilterValue")
	proto.RegisterType((*GetPageReq)(nil), "cloudwalker.GetPageReq")
	proto.RegisterType((*DeletePageReq)(nil), "cloudwalker.DeletePageReq")
	proto.RegisterType((*ResultPage)(nil), "cloudwalker.ResultPage")
	proto.RegisterType((*ResultRow)(nil), "cloudwalker.ResultRow")
	proto.RegisterType((*Content)(nil), "cloudwalker.Content")
	proto.RegisterType((*Play)(nil), "cloudwalker.Play")
	proto.RegisterType((*DropDownReq)(nil), "cloudwalker.DropDownReq")
	proto.RegisterType((*DropDownResp)(nil), "cloudwalker.DropDownResp")
}

func init() {
	proto.RegisterFile("page.proto", fileDescriptor_f14a105a5ef2e917)
}

var fileDescriptor_f14a105a5ef2e917 = []byte{
	// 1814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6f, 0x23, 0x57,
	0x19, 0xef, 0xf8, 0x12, 0xdb, 0x9f, 0xb3, 0xdb, 0xd9, 0xc3, 0x6e, 0x76, 0xd6, 0xe9, 0xd6, 0x07,
	0xb3, 0x85, 0x74, 0x48, 0x6c, 0xc7, 0x41, 0x40, 0xb7, 0xa4, 0x90, 0xcb, 0xa6, 0x0a, 0x0a, 0xed,
	0x32, 0xc9, 0x76, 0x2b, 0x0a, 0x1b, 0x26, 0x9e, 0x93, 0xd9, 0xa3, 0x8c, 0xe7, 0x4c, 0x67, 0x8e,
	0xe3, 0x9a, 0xaa, 0x12, 0xe2, 0x89, 0x27, 0x5e, 0x78, 0xe0, 0x15, 0x09, 0xf1, 0xcc, 0x9f, 0xc1,
	0x0b, 0x6f, 0xfc, 0x01, 0x96, 0x2c, 0xfe, 0x0d, 0x2e, 0xfa, 0xce, 0x99, 0xf1, 0x6d, 0x9d, 0x45,
	0x48, 0x44, 0x8a, 0x3c, 0xe7, 0x7c, 0xf7, 0xdb, 0xef, 0x3b, 0x00, 0x91, 0xeb, 0xb3, 0x66, 0x14,
	0x0b, 0x29, 0x48, 0xb5, 0x1b, 0x88, 0xbe, 0x37, 0x70, 0x83, 0x2b, 0x16, 0xd7, 0xd6, 0x7d, 0x21,
	0xfc, 0x80, 0xb5, 0x14, 0xe9, 0xa2, 0x7f, 0xd9, 0x62, 0xbd, 0x48, 0x0e, 0x35, 0x67, 0xad, 0xbe,
	0x48, 0x94, 0xbc, 0xc7, 0x12, 0xe9, 0xf6, 0xa2, 0x94, 0xe1, 0xad, 0x94, 0xc1, 0x8d, 0x78, 0xcb,
	0x0d, 0x43, 0x21, 0x5d, 0xc9, 0x45, 0x98, 0xa4, 0xd4, 0x4d, 0xf5, 0xd3, 0xdd, 0xf2, 0x59, 0xb8,
	0x95, 0x0c, 0x5c, 0xdf, 0x67, 0x71, 0x4b, 0x44, 0x8a, 0x63, 0x09, 0xf7, 0x77, 0x7d, 0x2e, 0x5f,
	0xf6, 0x2f, 0x9a, 0x5d, 0xd1, 0x6b, 0xf5, 0x06, 0x5c, 0x5e, 0x89, 0x41, 0xcb, 0x17, 0x5b, 0x8a,
	0xb8, 0x75, 0xed, 0x06, 0xdc, 0x73, 0xa5, 0x88, 0x93, 0xd6, 0xe4, 0x53, 0xcb, 0x35, 0xfe, 0x96,
	0x83, 0xc2, 0x53, 0xd7, 0x67, 0x64, 0x0f, 0x2a, 0x18, 0xe5, 0x79, 0xe8, 0xf6, 0x98, 0x65, 0x50,
	0x63, 0xa3, 0xb2, 0xff, 0x68, 0x3c, 0xaa, 0x53, 0x6a, 0xd8, 0x35, 0x64, 0xa0, 0x1f, 0xb9, 0x3d,
	0x46, 0xbb, 0xca, 0x32, 0xbd, 0x60, 0x54, 0x47, 0xfa, 0xa9, 0xe1, 0x94, 0x51, 0x0c, 0x89, 0x64,
	0x3d, 0x55, 0x11, 0x08, 0x5f, 0x58, 0x79, 0x54, 0xa1, 0x89, 0x27, 0xc2, 0x17, 0xa4, 0x01, 0xf9,
	0x58, 0x0c, 0xac, 0x02, 0xcd, 0x6f, 0x54, 0x3b, 0x66, 0x73, 0x26, 0x8b, 0x4d, 0x47, 0x0c, 0x1c,
	0x24, 0x92, 0x6d, 0x28, 0x77, 0xdd, 0x58, 0xf4, 0x13, 0x16, 0x58, 0x45, 0xc5, 0x78, 0x6f, 0x8e,
	0xf1, 0x20, 0x25, 0x3a, 0x13, 0x36, 0x72, 0x1f, 0x4a, 0xca, 0x26, 0xf7, 0xac, 0x15, 0x65, 0x71,
	0x05, 0x8f, 0xc7, 0x1e, 0x79, 0x0f, 0xa0, 0x1b, 0x33, 0x57, 0x32, 0xef, 0xdc, 0x95, 0x56, 0x89,
	0x1a, 0x1b, 0xd5, 0x4e, 0xad, 0xa9, 0x33, 0xde, 0xcc, 0x4a, 0xd2, 0x3c, 0xcb, 0x4a, 0xe2, 0x54,
	0x52, 0xee, 0x3d, 0x89, 0xa2, 0xfd, 0xc8, 0xcb, 0x44, 0xcb, 0xff, 0x5d, 0x34, 0xe5, 0xde, 0x93,
	0x8d, 0x7f, 0xe6, 0xa0, 0x9c, 0x79, 0x49, 0xde, 0x87, 0x15, 0xe9, 0xc6, 0x3e, 0x93, 0x69, 0x3e,
	0xbf, 0x31, 0x1e, 0xd5, 0xeb, 0xd4, 0xb0, 0x1f, 0x1c, 0x32, 0x16, 0x05, 0x3c, 0xbc, 0x5a, 0x96,
	0xce, 0x54, 0x84, 0x3c, 0xc1, 0xc0, 0xba, 0x57, 0xae, 0xcf, 0xac, 0x9c, 0x92, 0xfe, 0xf6, 0x78,
	0x54, 0xff, 0x16, 0x35, 0xec, 0xaf, 0xef, 0x45, 0x11, 0x7d, 0xaa, 0x49, 0x37, 0x16, 0x25, 0x93,
	0xc5, 0xb2, 0xf2, 0x1e, 0x26, 0xa8, 0x1f, 0x07, 0xba, 0x26, 0xd3, 0xb2, 0x1e, 0x23, 0x81, 0x3e,
	0x8b, 0x83, 0xa5, 0x65, 0x55, 0x62, 0xcf, 0xe2, 0x80, 0xfc, 0x10, 0x8a, 0x92, 0xcb, 0x80, 0x59,
	0x05, 0x25, 0xfe, 0xee, 0x78, 0x54, 0x7f, 0x87, 0x1a, 0x76, 0x3d, 0x8b, 0x93, 0x9e, 0x21, 0x75,
	0x99, 0x0e, 0x2d, 0x47, 0x38, 0x14, 0x79, 0xe8, 0xb1, 0x2f, 0xac, 0x22, 0x35, 0x36, 0x8a, 0xfb,
	0xa7, 0xe3, 0x51, 0xfd, 0x63, 0x80, 0x17, 0x9f, 0xb5, 0xb7, 0xb6, 0xdb, 0xed, 0x5f, 0xd8, 0x8f,
	0xcc, 0x7f, 0x67, 0x7f, 0x86, 0xe5, 0x51, 0xc3, 0xee, 0x4c, 0x34, 0x1f, 0xa3, 0x18, 0xed, 0xf5,
	0x13, 0xa5, 0xd7, 0xa5, 0x1e, 0xf7, 0xb9, 0xa4, 0x6e, 0xe8, 0xd1, 0x0f, 0x76, 0x69, 0x5b, 0x7d,
	0xfc, 0x80, 0x6e, 0xb7, 0xdb, 0x4d, 0x47, 0x5b, 0x68, 0xfc, 0xa5, 0x04, 0x79, 0x47, 0x0c, 0xc8,
	0xef, 0x0c, 0x80, 0x58, 0x0c, 0xce, 0x03, 0x77, 0x28, 0xfa, 0x3a, 0xff, 0xb7, 0x3b, 0x6b, 0x8b,
	0x5d, 0x77, 0xa2, 0xa8, 0xfb, 0xcf, 0xc7, 0xa3, 0xfa, 0x29, 0x35, 0xec, 0x13, 0x47, 0x0c, 0xa8,
	0xbe, 0x9b, 0xd8, 0x4c, 0x98, 0x6c, 0xd2, 0x13, 0x37, 0xf4, 0x92, 0xae, 0x1b, 0x31, 0xba, 0x4b,
	0xdb, 0x9b, 0xf4, 0xa9, 0x88, 0x65, 0xec, 0x72, 0x49, 0x77, 0xe9, 0xf6, 0x26, 0x3d, 0xfd, 0xbc,
	0xef, 0xc6, 0x48, 0xe9, 0x6c, 0xd2, 0x03, 0x1e, 0x77, 0x03, 0xfc, 0xde, 0x69, 0xfe, 0xd6, 0x30,
	0x9c, 0x4a, 0x9c, 0xd9, 0x20, 0x1f, 0x40, 0x19, 0xfd, 0x51, 0xd3, 0x95, 0x9b, 0xef, 0x06, 0xb4,
	0x7a, 0x63, 0x1d, 0x63, 0x31, 0x50, 0xb3, 0xd5, 0x07, 0x54, 0x76, 0xae, 0xf3, 0x98, 0x57, 0x79,
	0xfc, 0x74, 0x3c, 0xaa, 0x9f, 0xbd, 0x2e, 0x8f, 0xdf, 0x43, 0xcd, 0x37, 0xa7, 0x90, 0x87, 0x54,
	0xbe, 0x64, 0x34, 0x76, 0x43, 0x9f, 0x51, 0x71, 0x49, 0xdb, 0x74, 0x0b, 0x73, 0x49, 0x9b, 0x0e,
	0xba, 0xaa, 0xe4, 0xc8, 0x1e, 0x54, 0xd1, 0xec, 0x25, 0x0f, 0x24, 0x8b, 0x93, 0x74, 0x7a, 0xe9,
	0x62, 0x1e, 0xf1, 0xff, 0x48, 0xb3, 0x3c, 0x09, 0x65, 0x3c, 0x74, 0x30, 0xf7, 0xe9, 0x05, 0xf9,
	0xa3, 0xa1, 0x43, 0x4f, 0x44, 0x2c, 0xd3, 0xa9, 0x7e, 0xb8, 0x4c, 0xc1, 0xa9, 0x88, 0xa5, 0x92,
	0xde, 0xbf, 0x1c, 0x8f, 0xea, 0x17, 0x50, 0x79, 0xf1, 0xd9, 0xd6, 0xf6, 0x56, 0x07, 0xe3, 0xfa,
	0xd7, 0x34, 0xae, 0x1c, 0x35, 0xec, 0x23, 0x8c, 0x0b, 0xd9, 0xe7, 0xab, 0xb4, 0xb5, 0x4d, 0x2f,
	0x45, 0x4c, 0xd1, 0x0e, 0xf5, 0x58, 0xd2, 0x65, 0xa1, 0xc7, 0x43, 0x5f, 0x85, 0x3a, 0x43, 0x71,
	0x33, 0x42, 0x53, 0x25, 0x17, 0xd5, 0x10, 0x0a, 0xab, 0xe8, 0xa1, 0xe4, 0x01, 0x02, 0x49, 0x62,
	0xad, 0xd0, 0xfc, 0x46, 0x45, 0x05, 0x71, 0xc6, 0x03, 0x76, 0xec, 0x25, 0xe4, 0xcf, 0x69, 0x10,
	0x72, 0x18, 0x31, 0x05, 0x26, 0xb7, 0x3b, 0x77, 0x17, 0x83, 0x38, 0x1b, 0x46, 0x6c, 0x5f, 0x8e,
	0x47, 0xf5, 0xc8, 0xbe, 0x42, 0x0f, 0xf1, 0x3c, 0xef, 0xe1, 0x13, 0x8f, 0x4b, 0x11, 0x73, 0x37,
	0xc0, 0x3e, 0xa2, 0x9b, 0xd4, 0x61, 0x5d, 0xd1, 0xeb, 0xb1, 0xd0, 0x53, 0x50, 0x7e, 0x7e, 0xb0,
	0x4f, 0x75, 0x4b, 0x1d, 0x0e, 0x43, 0xb7, 0xc7, 0xbb, 0x54, 0x37, 0xd5, 0x22, 0xd7, 0x11, 0xde,
	0xef, 0x6c, 0xd2, 0xe7, 0xec, 0x82, 0xee, 0xd2, 0xef, 0x60, 0xa3, 0x61, 0x24, 0x68, 0x8e, 0x58,
	0x50, 0x4a, 0x5e, 0xf6, 0x2f, 0x2f, 0x03, 0xa6, 0x70, 0xab, 0xec, 0x64, 0xc7, 0xda, 0xcf, 0xe0,
	0xcd, 0x85, 0x2a, 0x11, 0x13, 0xf2, 0x57, 0x6c, 0xa8, 0xc1, 0xc9, 0xc1, 0x4f, 0xb2, 0x0d, 0xc5,
	0x6b, 0x37, 0xe8, 0xeb, 0x16, 0xad, 0x76, 0xd6, 0x17, 0x43, 0xd4, 0xe2, 0x9f, 0x20, 0x8b, 0xa3,
	0x39, 0x1f, 0xe7, 0xbe, 0x6f, 0xd4, 0x1e, 0xc3, 0xea, 0x6c, 0x01, 0x97, 0x28, 0xbe, 0x3b, 0xab,
	0xf8, 0xce, 0x8c, 0x6c, 0x63, 0x03, 0x6e, 0xcf, 0x2b, 0x26, 0x6b, 0xb0, 0xa2, 0xc8, 0x89, 0x65,
	0xa8, 0x3a, 0xa4, 0xa7, 0xc6, 0x31, 0xc0, 0x87, 0x4c, 0xe2, 0x2e, 0x72, 0xd8, 0xe7, 0xe4, 0xfd,
	0x29, 0xf0, 0x6b, 0x74, 0x6d, 0x8c, 0x47, 0xf5, 0xb7, 0xa9, 0x61, 0x5b, 0x6a, 0x5b, 0x71, 0x6f,
	0x29, 0xb8, 0xea, 0xe5, 0xd0, 0x38, 0x81, 0x5b, 0x87, 0x2c, 0x60, 0x92, 0xfd, 0x5f, 0xb4, 0xfd,
	0xc9, 0x00, 0x70, 0x58, 0xd2, 0x0f, 0x94, 0x73, 0xb3, 0x2b, 0xc9, 0x98, 0x5b, 0x49, 0xeb, 0xb3,
	0x2b, 0x36, 0x37, 0xdd, 0x8f, 0x6a, 0xc0, 0x77, 0xa0, 0x92, 0x2d, 0xb5, 0xc4, 0xca, 0xbf, 0x6e,
	0xf9, 0x4d, 0xf9, 0x88, 0x0d, 0x85, 0x58, 0x0c, 0xb2, 0xb9, 0x5c, 0xc0, 0x37, 0xe5, 0x11, 0xee,
	0x56, 0xc5, 0xd3, 0x10, 0x50, 0x99, 0x5c, 0x91, 0x07, 0x33, 0x70, 0xa4, 0x9d, 0x9c, 0x20, 0xcd,
	0xfa, 0x2c, 0xd2, 0xa0, 0x97, 0xc5, 0x19, 0x3c, 0xb0, 0x71, 0x17, 0x04, 0x2c, 0xf3, 0x70, 0x7e,
	0x06, 0x0e, 0x44, 0x28, 0x59, 0x28, 0x1d, 0xcd, 0xd2, 0xf8, 0x75, 0x0e, 0x4a, 0xe9, 0x15, 0xd6,
	0x5f, 0xef, 0x90, 0xb2, 0x32, 0x96, 0x2e, 0x86, 0x35, 0x58, 0x89, 0x44, 0x22, 0x59, 0x9c, 0x55,
	0x5a, 0x9f, 0x48, 0x0d, 0xca, 0x11, 0x62, 0x2c, 0x77, 0xa5, 0x95, 0x53, 0x94, 0xc9, 0x99, 0xbc,
	0x0b, 0x05, 0x35, 0x84, 0x79, 0x35, 0x84, 0xf3, 0x29, 0xc2, 0x69, 0xc5, 0x31, 0x70, 0x14, 0x0b,
	0x79, 0x04, 0xb7, 0x79, 0x72, 0xee, 0x31, 0xe9, 0xf2, 0xe0, 0x1c, 0x13, 0xad, 0x36, 0x58, 0xd9,
	0x59, 0xe5, 0xc9, 0xa1, 0xba, 0x54, 0xe5, 0x7a, 0x08, 0xd0, 0xd5, 0x5e, 0x62, 0xc5, 0x8a, 0xca,
	0xbf, 0x4a, 0x7a, 0x73, 0xec, 0x91, 0x77, 0xa0, 0x10, 0x05, 0xee, 0x50, 0x61, 0x42, 0xb5, 0x73,
	0x67, 0xce, 0xde, 0xd3, 0xc0, 0x1d, 0x3a, 0x8a, 0xac, 0x1a, 0x9c, 0x7b, 0x4c, 0x58, 0x25, 0xe5,
	0xaf, 0x3e, 0x34, 0xfe, 0x60, 0x40, 0x01, 0x99, 0xf0, 0x65, 0xd3, 0x13, 0x21, 0x93, 0xfc, 0x57,
	0x4c, 0x99, 0x58, 0xf4, 0xfc, 0x27, 0x29, 0xd1, 0x99, 0xb0, 0x61, 0x72, 0x66, 0x5f, 0x0f, 0x93,
	0x87, 0xc1, 0x1a, 0xac, 0x24, 0xa2, 0x1f, 0x77, 0xb3, 0x16, 0x4a, 0x4f, 0x38, 0xfa, 0xd9, 0x83,
	0x41, 0xbf, 0xbd, 0x26, 0x6f, 0x00, 0x92, 0xa6, 0x4c, 0xed, 0x6f, 0x9d, 0x9b, 0xc6, 0x05, 0x54,
	0x0f, 0x63, 0x11, 0x1d, 0x8a, 0x41, 0x88, 0xfd, 0x7f, 0x0a, 0xc5, 0x4b, 0xce, 0x82, 0xac, 0xfb,
	0x77, 0xc7, 0xa3, 0xfa, 0x7b, 0xd4, 0xb0, 0x77, 0x0e, 0xf7, 0xe9, 0x25, 0x0f, 0x98, 0xa7, 0x71,
	0x8c, 0x7d, 0xc1, 0x13, 0x99, 0x50, 0x29, 0xa8, 0xcf, 0x24, 0x4d, 0xfa, 0xbe, 0xcf, 0x12, 0xc9,
	0x3c, 0xaa, 0x07, 0x14, 0x77, 0x08, 0x97, 0x6a, 0xef, 0x2b, 0x5d, 0x8d, 0x6f, 0xc2, 0xea, 0xd4,
	0x46, 0x12, 0xa1, 0xe7, 0xb1, 0xea, 0xc0, 0xac, 0xdc, 0xfa, 0x64, 0xff, 0x08, 0x2a, 0x93, 0x65,
	0x4c, 0x6e, 0x41, 0x65, 0xb2, 0x6e, 0xcd, 0x37, 0xc8, 0x2a, 0x94, 0xb3, 0x75, 0x6b, 0x1a, 0x04,
	0x60, 0x45, 0xaf, 0x5b, 0x33, 0x87, 0xdf, 0x7a, 0xdd, 0x9a, 0x79, 0xfb, 0xe7, 0x50, 0x4a, 0x01,
	0x18, 0xe5, 0x27, 0x30, 0x6b, 0xbe, 0x41, 0xee, 0xc1, 0x9d, 0x57, 0x50, 0xd6, 0x34, 0x48, 0x15,
	0x4a, 0x29, 0xc8, 0x9a, 0xb9, 0x65, 0x3c, 0x47, 0x66, 0x9e, 0x94, 0x20, 0xff, 0x9c, 0x5d, 0x98,
	0x05, 0xfb, 0x31, 0x94, 0xb3, 0xfa, 0x90, 0x32, 0x14, 0x8e, 0x62, 0x86, 0x9e, 0x95, 0xf1, 0xe1,
	0xcc, 0x3d, 0xd3, 0x20, 0x26, 0xac, 0x9e, 0xf6, 0x2f, 0x92, 0x6e, 0xcc, 0xd5, 0xf3, 0xdc, 0xcc,
	0x21, 0xcd, 0x61, 0xa1, 0x34, 0xf3, 0xf6, 0x0b, 0x28, 0x67, 0x5d, 0x89, 0xae, 0xa9, 0x27, 0x17,
	0x5e, 0x98, 0x6f, 0xe0, 0xf1, 0x13, 0xec, 0x12, 0x75, 0x34, 0xc8, 0x9b, 0x50, 0x3d, 0x62, 0xae,
	0xec, 0xc7, 0x9a, 0x9e, 0x23, 0x77, 0xe0, 0xd6, 0x9e, 0x77, 0xcd, 0x62, 0xc9, 0x13, 0x7d, 0x95,
	0x47, 0x4b, 0x19, 0x0c, 0xa8, 0x9b, 0x42, 0xe7, 0xaf, 0x45, 0xa8, 0x62, 0x1b, 0x9f, 0xb2, 0xf8,
	0x9a, 0x77, 0x19, 0xf9, 0x31, 0xc0, 0x81, 0x7a, 0xc8, 0xaa, 0xde, 0x5e, 0x68, 0x57, 0xd7, 0x67,
	0xb5, 0x57, 0xaf, 0x1a, 0x6b, 0xbf, 0xf9, 0xfb, 0x3f, 0x7e, 0x9f, 0x33, 0x1b, 0xd5, 0x56, 0x77,
	0x22, 0xfa, 0xd8, 0xb0, 0xc9, 0x4f, 0xa1, 0x94, 0x02, 0x2e, 0xb9, 0x3f, 0x27, 0x35, 0x85, 0xe1,
	0x65, 0xea, 0x6a, 0x4a, 0xdd, 0x5d, 0x42, 0x5a, 0xbe, 0xe6, 0x6b, 0x7d, 0x99, 0xe2, 0xe1, 0x57,
	0xe4, 0x63, 0xa8, 0x7e, 0xc8, 0xe4, 0x5e, 0xa0, 0x46, 0x2f, 0x21, 0x6b, 0xaf, 0xbc, 0xaa, 0x9f,
	0x20, 0xb8, 0x2e, 0xd3, 0xfa, 0x35, 0xa5, 0xf5, 0x16, 0xa9, 0xa2, 0xd6, 0x54, 0x41, 0xdb, 0x20,
	0x67, 0x00, 0xcf, 0xd4, 0xeb, 0xfb, 0x7f, 0x88, 0x97, 0x2a, 0x55, 0xb5, 0xda, 0xbd, 0x56, 0x7f,
	0x22, 0x3a, 0xf5, 0x11, 0x23, 0x3f, 0x07, 0x98, 0xee, 0x07, 0x52, 0x9b, 0x53, 0x31, 0xb7, 0x38,
	0x6a, 0x37, 0x44, 0xd0, 0x78, 0xa8, 0x6c, 0xdc, 0xb7, 0xef, 0xb5, 0xbc, 0x09, 0xff, 0x4c, 0x1e,
	0xce, 0xa1, 0xea, 0xb0, 0x44, 0x04, 0xd7, 0xec, 0xf5, 0xe9, 0xbd, 0xbf, 0x04, 0xd2, 0x55, 0x0c,
	0x6f, 0x2b, 0xfd, 0x16, 0x59, 0x6b, 0xc5, 0x53, 0x3d, 0x33, 0x06, 0x3e, 0x82, 0xd2, 0x81, 0x2b,
	0xdd, 0x40, 0xf8, 0x37, 0x26, 0xf9, 0x46, 0xdd, 0xa6, 0xd2, 0x0d, 0xa4, 0xdc, 0xea, 0x6a, 0x15,
	0x6d, 0x83, 0xfc, 0x52, 0x15, 0x2e, 0x1b, 0x67, 0x62, 0xcd, 0xa7, 0x64, 0x8a, 0x24, 0xb5, 0x07,
	0x37, 0x50, 0x92, 0xa8, 0xf1, 0x96, 0xd2, 0xbb, 0x46, 0xee, 0x62, 0x09, 0x33, 0x4a, 0xeb, 0x4b,
	0x05, 0x16, 0x5f, 0x5d, 0xac, 0x28, 0xf7, 0x76, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x23, 0x5a,
	0x3f, 0x33, 0x6d, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PageServiceClient is the client API for PageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PageServiceClient interface {
	// Always create a new page. we will not check if the page already exist or not.
	CreatePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
	// will get the page from its page ID.
	GetPage(ctx context.Context, in *GetPageReq, opts ...grpc.CallOption) (*Page, error)
	// will get all the page from the DB to create a Catlog(Book).
	GetAllPages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (PageService_GetAllPagesClient, error)
	//replace a particular page of the given ID
	UpdatePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error)
	// Delete a page of the given ID.
	DeletePage(ctx context.Context, in *DeletePageReq, opts ...grpc.CallOption) (*empty.Empty, error)
	// Resolve the page to actual content to show in the UI.
	ResolvePage(ctx context.Context, in *GetPageReq, opts ...grpc.CallOption) (*ResultPage, error)
	// get All the resolved pages to form a catlog
	Catalog(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (PageService_CatalogClient, error)
	// INTERNAL but can used as seperatly to get all the possible value of a filed in DB.
	GetDropDown(ctx context.Context, in *DropDownReq, opts ...grpc.CallOption) (*DropDownResp, error)
}

type pageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageServiceClient(cc grpc.ClientConnInterface) PageServiceClient {
	return &pageServiceClient{cc}
}

func (c *pageServiceClient) CreatePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/cloudwalker.PageService/CreatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetPage(ctx context.Context, in *GetPageReq, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/cloudwalker.PageService/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) GetAllPages(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (PageService_GetAllPagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PageService_serviceDesc.Streams[0], "/cloudwalker.PageService/GetAllPages", opts...)
	if err != nil {
		return nil, err
	}
	x := &pageServiceGetAllPagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PageService_GetAllPagesClient interface {
	Recv() (*Page, error)
	grpc.ClientStream
}

type pageServiceGetAllPagesClient struct {
	grpc.ClientStream
}

func (x *pageServiceGetAllPagesClient) Recv() (*Page, error) {
	m := new(Page)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pageServiceClient) UpdatePage(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Page, error) {
	out := new(Page)
	err := c.cc.Invoke(ctx, "/cloudwalker.PageService/UpdatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) DeletePage(ctx context.Context, in *DeletePageReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/cloudwalker.PageService/DeletePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) ResolvePage(ctx context.Context, in *GetPageReq, opts ...grpc.CallOption) (*ResultPage, error) {
	out := new(ResultPage)
	err := c.cc.Invoke(ctx, "/cloudwalker.PageService/ResolvePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageServiceClient) Catalog(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (PageService_CatalogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PageService_serviceDesc.Streams[1], "/cloudwalker.PageService/Catalog", opts...)
	if err != nil {
		return nil, err
	}
	x := &pageServiceCatalogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PageService_CatalogClient interface {
	Recv() (*ResultPage, error)
	grpc.ClientStream
}

type pageServiceCatalogClient struct {
	grpc.ClientStream
}

func (x *pageServiceCatalogClient) Recv() (*ResultPage, error) {
	m := new(ResultPage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pageServiceClient) GetDropDown(ctx context.Context, in *DropDownReq, opts ...grpc.CallOption) (*DropDownResp, error) {
	out := new(DropDownResp)
	err := c.cc.Invoke(ctx, "/cloudwalker.PageService/GetDropDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageServiceServer is the server API for PageService service.
type PageServiceServer interface {
	// Always create a new page. we will not check if the page already exist or not.
	CreatePage(context.Context, *Page) (*Page, error)
	// will get the page from its page ID.
	GetPage(context.Context, *GetPageReq) (*Page, error)
	// will get all the page from the DB to create a Catlog(Book).
	GetAllPages(*empty.Empty, PageService_GetAllPagesServer) error
	//replace a particular page of the given ID
	UpdatePage(context.Context, *Page) (*Page, error)
	// Delete a page of the given ID.
	DeletePage(context.Context, *DeletePageReq) (*empty.Empty, error)
	// Resolve the page to actual content to show in the UI.
	ResolvePage(context.Context, *GetPageReq) (*ResultPage, error)
	// get All the resolved pages to form a catlog
	Catalog(*empty.Empty, PageService_CatalogServer) error
	// INTERNAL but can used as seperatly to get all the possible value of a filed in DB.
	GetDropDown(context.Context, *DropDownReq) (*DropDownResp, error)
}

// UnimplementedPageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPageServiceServer struct {
}

func (*UnimplementedPageServiceServer) CreatePage(ctx context.Context, req *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (*UnimplementedPageServiceServer) GetPage(ctx context.Context, req *GetPageReq) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedPageServiceServer) GetAllPages(req *empty.Empty, srv PageService_GetAllPagesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllPages not implemented")
}
func (*UnimplementedPageServiceServer) UpdatePage(ctx context.Context, req *Page) (*Page, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePage not implemented")
}
func (*UnimplementedPageServiceServer) DeletePage(ctx context.Context, req *DeletePageReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePage not implemented")
}
func (*UnimplementedPageServiceServer) ResolvePage(ctx context.Context, req *GetPageReq) (*ResultPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePage not implemented")
}
func (*UnimplementedPageServiceServer) Catalog(req *empty.Empty, srv PageService_CatalogServer) error {
	return status.Errorf(codes.Unimplemented, "method Catalog not implemented")
}
func (*UnimplementedPageServiceServer) GetDropDown(ctx context.Context, req *DropDownReq) (*DropDownResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDropDown not implemented")
}

func RegisterPageServiceServer(s *grpc.Server, srv PageServiceServer) {
	s.RegisterService(&_PageService_serviceDesc, srv)
}

func _PageService_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.PageService/CreatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).CreatePage(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.PageService/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetPage(ctx, req.(*GetPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_GetAllPages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PageServiceServer).GetAllPages(m, &pageServiceGetAllPagesServer{stream})
}

type PageService_GetAllPagesServer interface {
	Send(*Page) error
	grpc.ServerStream
}

type pageServiceGetAllPagesServer struct {
	grpc.ServerStream
}

func (x *pageServiceGetAllPagesServer) Send(m *Page) error {
	return x.ServerStream.SendMsg(m)
}

func _PageService_UpdatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).UpdatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.PageService/UpdatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).UpdatePage(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.PageService/DeletePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).DeletePage(ctx, req.(*DeletePageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_ResolvePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).ResolvePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.PageService/ResolvePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).ResolvePage(ctx, req.(*GetPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageService_Catalog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PageServiceServer).Catalog(m, &pageServiceCatalogServer{stream})
}

type PageService_CatalogServer interface {
	Send(*ResultPage) error
	grpc.ServerStream
}

type pageServiceCatalogServer struct {
	grpc.ServerStream
}

func (x *pageServiceCatalogServer) Send(m *ResultPage) error {
	return x.ServerStream.SendMsg(m)
}

func _PageService_GetDropDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDownReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageServiceServer).GetDropDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudwalker.PageService/GetDropDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageServiceServer).GetDropDown(ctx, req.(*DropDownReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cloudwalker.PageService",
	HandlerType: (*PageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _PageService_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _PageService_GetPage_Handler,
		},
		{
			MethodName: "UpdatePage",
			Handler:    _PageService_UpdatePage_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _PageService_DeletePage_Handler,
		},
		{
			MethodName: "ResolvePage",
			Handler:    _PageService_ResolvePage_Handler,
		},
		{
			MethodName: "GetDropDown",
			Handler:    _PageService_GetDropDown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllPages",
			Handler:       _PageService_GetAllPages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Catalog",
			Handler:       _PageService_Catalog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "page.proto",
}
